# Generated by Django 4.1.7 on 2023-05-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=128, verbose_name='Descripcion')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=128, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('mail', models.EmailField(max_length=128, verbose_name='Mail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=128, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('mail', models.EmailField(max_length=128, verbose_name='Mail')),
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='dni')),
                ('obra_social', models.CharField(max_length=128, null=True, verbose_name='Obra_social')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.CharField(max_length=128, verbose_name='horario_turno')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.paciente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dni',), name='unique_dni_combination'),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.especialidad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='paciente',
            field=models.ManyToManyField(through='AppPoliconsultorio.Turno', to='AppPoliconsultorio.paciente'),
        ),
        migrations.AddConstraint(
            model_name='especialidad',
            constraint=models.UniqueConstraint(fields=('codigo', 'descripcion'), name='unique_codigo_descripcion_combination'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha', 'hora'), name='unique_medico_fecha_hora_combination'),
        ),
    ]
