# Generated by Django 4.2 on 2023-05-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_id', models.IntegerField(verbose_name='Código de especialidad')),
                ('descripcion', models.CharField(max_length=128, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('matricula', models.CharField(max_length=8, verbose_name='Matrícula')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=25, verbose_name='Nombre Paciente')),
                ('apellido_paciente', models.CharField(max_length=15, verbose_name='Apellido Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('horario', models.CharField(max_length=5, verbose_name='Horario')),
                ('especialidad', models.ManyToManyField(to='AppPoliconsultorio.especialidades')),
                ('medico', models.ManyToManyField(to='AppPoliconsultorio.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.pacientes')),
            ],
        ),
    ]
