# Generated by Django 4.2 on 2023-05-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha Nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1, verbose_name='Genero')),
                ('obra_social', models.CharField(max_length=128, null=True, verbose_name='Obra_social')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(max_length=128, verbose_name='Horario_turno')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.paciente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dni',), name='unique_dni_combination'),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.especialidad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='pacientes',
            field=models.ManyToManyField(through='AppPoliconsultorio.Turno', to='AppPoliconsultorio.paciente'),
        ),
        migrations.AddConstraint(
            model_name='especialidad',
            constraint=models.UniqueConstraint(fields=('codigo', 'descripcion'), name='unique_codigo_descripcion_combination'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha', 'hora'), name='unique_medico_fecha_hora_combination'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('matricula',), name='unique_matricula_combination'),
        ),
    ]
