# Generated by Django 4.1.7 on 2023-05-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='paciente',
            new_name='pacientes',
        ),
    ]
