# Generated by Django 4.2 on 2023-05-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.especialidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1, verbose_name='Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.paciente')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.DeleteModel(
            name='Medicos',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.AddField(
            model_name='medico',
            name='pacientes',
            field=models.ManyToManyField(through='AppPoliconsultorio.Turno', to='AppPoliconsultorio.paciente'),
        ),
    ]
