# Generated by Django 4.2 on 2023-05-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='email',
            new_name='mail',
        ),
    ]
