# Generated by Django 4.2 on 2023-05-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0002_especialidad_medico_paciente_turno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='email',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(max_length=128, null=True, verbose_name='Obra_social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(max_length=128, verbose_name='Horario_turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.paciente'),
        ),
        migrations.AddConstraint(
            model_name='especialidad',
            constraint=models.UniqueConstraint(fields=('codigo', 'descripcion'), name='unique_codigo_descripcion_combination'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('matricula',), name='unique_matricula_combination'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dni',), name='unique_dni_combination'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha', 'hora'), name='unique_medico_fecha_hora_combination'),
        ),
    ]
