# Generated by Django 4.1.7 on 2023-05-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0002_rename_paciente_medico_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matricula'),
        ),
    ]
