# Generated by Django 4.1.7 on 2023-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0003_medico_matricula_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='medico',
        #     constraint=models.UniqueConstraint(fields=('matricula',), name='unique_matricula_combination'),
        # ),
    ]
