# Generated by Django 4.1.7 on 2023-06-03 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0004_paciente_fecha_nacimiento_paciente_genero_and_more'),
    ]

    operations = [
    ]
