# Generated by Django 4.2 on 2023-06-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0004_paciente_fecha_nacimiento_paciente_genero_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='paciente',
        #     name='fecha_nacimiento',
        #     field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        # ),
        # migrations.AddField(
        #     model_name='paciente',
        #     name='genero',
        #     field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Genero'),
        # ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='mail',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        # migrations.AlterField(
        #     model_name='medico',
        #     name='matricula',
        #     field=models.IntegerField(null=True, verbose_name='Matricula'),
        # ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='mail',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(max_length=128, verbose_name='Horario_turno'),
        ),
    ]
