# Generated by Django 4.1.7 on 2023-06-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPoliconsultorio', '0005_alter_especialidad_options_paciente_fecha_nacimiento_and_more'),
        ('AppPoliconsultorio', '0005_paciente_fecha_nacimiento_paciente_genero_and_more'),
    ]

    operations = [
    ]
