# Generated by Django 4.1.7 on 2023-06-11 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPoliconsultorio', '0006_merge_20230611_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        #migrations.AlterField(
        #    model_name='medico',
        #    name='matricula',
        #    field=models.IntegerField(null=True, verbose_name='Matricula'),
        #),
        #migrations.AlterField(
        #    model_name='turno',
        #    name='hora',
        #    field=models.CharField(choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=128, verbose_name='Horario_turno'),
        #),
        #migrations.AlterField(
        #    model_name='turno',
        #    name='paciente',
        #    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPoliconsultorio.paciente'),
        #),
        #migrations.AddConstraint(
        #    model_name='medico',
        #    constraint=models.UniqueConstraint(fields=('matricula',), name='unique_matricula_combination'),
        #),
    ]
